## 1.导入模块


In [189]:
# cu118 表示支持 GPU 加速
import torch

torch.__version__

'2.0.0+cu118'

## 2.张量简介


### 2.1创建张量

In [190]:
scalar = torch.tensor(7)
scalar

tensor(7)

检查张量维度

In [191]:
scalar.ndim

0

将Tensor转换成Python数字

In [192]:
# 仅适用于单元素张量
scalar.item()

7

创建向量

In [193]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

检查向量维度

In [194]:
vector.ndim

1

检查向量形状

In [195]:
vector.shape

torch.Size([2])

创建矩阵

In [196]:
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

检查矩阵维度

In [197]:
matrix.ndim

2

检查矩阵形状

In [198]:
matrix.shape

torch.Size([2, 2])

创建张量

In [199]:
t = torch.tensor([[[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]]])
t

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

检查张量维度

In [200]:
t.ndim

3

检查张量形状

In [201]:
t.shape

torch.Size([1, 3, 3])

### 2.2随机张量

In [202]:
random_tensor = torch.rand(size=(1, 28, 28))
random_tensor.shape

torch.Size([1, 28, 28])

常见图像形状

In [203]:
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape

torch.Size([3, 224, 224])

### 2.3零和一张量


创建全零张量

In [204]:
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

创建全一张量

In [205]:
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### 2.4创建指定范围的张量

In [206]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

创建一个类似于另一个张量的零的张量

In [207]:
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### 2.5张量数据类型


| 数据类型          | 类型               | CPU tensor           | GPU tensor                |
|---------------|------------------|----------------------|---------------------------|
| 32位浮点数        | torch.float32    | torch.FloatTensor    | torch.cuda.FloatTensor    |
| 64位浮点数        | torch.float64    | torch.DoubleTensor   | torch.cuda.DoubleTensor   |
| 16位浮点数        | torch.float16    | torch.HalfTensor     | torch.cuda.HalfTensor     |
| 16位浮点数        | torch.bfloat16   | torch.BFloat16Tensor | torch.cuda.BFloat16Tensor |
| 32位复数         | torch.complex32  | /                    | /                         |
| 64位复数         | torch.complex64  | /                    | /                         |
| 128位复数        | torch.complex128 | /                    | /                         |
| 8位整数（无符号）     | torch.uint8      | torch.ByteTensor     | torch.cuda.ByteTensor     |
| 8位整数（有符号）     | torch.int8       | torch.CharTensor     | torch.cuda.CharTensor     |
| 16位整数（有符号）    | torch.int16      | torch.ShortTensor    | torch.cuda.ShortTensor    |
| 32位整数（有符号）    | torch.int32      | torch.IntTensor      | torch.cuda.IntTensor      |
| 64位整数（有符号）    | torch.int64      | torch.LongTensor     | torch.cuda.LongTensor     |
| 布尔值           | torch.bool       | torch.BoolTensor     | torch.cuda.BoolTensor     |
| 量化的8位整数（无符号）  | torch.quint8     | torch.ByteTensor     | /                         |
| 量化的8位整数（有符号）  | torch.qint8      | torch.CharTensor     | /                         |
| 量化的32位整数（有符号） | torch.qint32     | torch.IntTensor      | /                         |
| 量化的4位整数（无符号）  | torch.quint4x2   | torch.ByteTensor     | /                         |


创建一些具有特定数据类型的`tensor`，使用`dtype`参数来做到这一点

PyTorch 中遇到的另外两个最常见的问题是数据类型和设备问题

- 一个张量是 `torch.float32` 另一个是 `torch.float16`
- 一个张量在 `CPU` 上，另一个在 `GPU` 上

In [208]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,  # 默认为无，即 torch.float32 或传递的任何数据类型
                               device=None,  # 默认为 None，它使用默认的张量类型
                               requires_grad=False)  # 如果为真，则记录对张量执行的操作，以便在反向传播期间自动计算梯度

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

`dtype`可以指定类型，创建一个 `torch.float16` 张量

In [209]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)  # torch.half would also work

float_16_tensor.dtype

torch.float16

## 3.获取张量信息

In [210]:
# 创建一个张量
some_tensor = torch.rand(3, 4)

# 查看张量信息
print(some_tensor) # 会打印张量的值
print(f"Shape of tensor: {some_tensor.shape}") # 打印张量的形状
print(f"Datatype of tensor: {some_tensor.dtype}") # 打印张量的数据类型
print(f"Device tensor is stored on: {some_tensor.device}")  # 打印张量所在的设备
# 将张量移动到 GPU
some_tensor = some_tensor.to("cuda")
print(f"Device tensor is stored on: {some_tensor.device}")  # 打印张量所在的设备

tensor([[0.8170, 0.5819, 0.7871, 0.7832],
        [0.3328, 0.6762, 0.3527, 0.1545],
        [0.5859, 0.7646, 0.9481, 0.5610]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
Device tensor is stored on: cuda:0


## 4.张量运算

### 4.1基本操作


In [211]:
# 加法
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [212]:
# 减法
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [213]:
# 乘法
tensor * 10

tensor([-90, -80, -70])

In [214]:
# 除法
tensor / 10

tensor([-0.9000, -0.8000, -0.7000])

Pytorch 中的张量运算与 numpy 中的类似，但是有一些不同之处

In [215]:
torch.multiply(tensor, 10) # 乘法

tensor([-90, -80, -70])

### 4.2矩阵乘法

机器学习和深度学习算法（如神经网络）中最常见的操作之一是矩阵乘法。

PyTorch 在方法中实现矩阵乘法功能`torch.matmul()`。

矩阵乘法的两个主要规则是:

- 内部尺寸必须匹配:
    - `(3, 2) @ (3, 2)` 不会计算
    - `(2, 3) @ (3, 2)` 会计算
    - `(3, 2) @ (2, 3)` 会计算

- 得到的矩阵的形状与外部维度相同:

    - `(2, 3) @ (3, 2)` -> `(2, 2)`
    - `(3, 2) @ (2, 3)` -> `(3, 3)`

> **注意:** Python中 "`@`" 是矩阵乘法的符号

可以手动进行矩阵乘法，但不推荐这样做，因为它很慢。相反，使用 PyTorch内置的 `torch.matmul()` 方法更快，更有效。

## 5.转置

由于大部分深度学习都是在矩阵上进行乘法和运算，而矩阵对可以组合的形状和大小有严格的规定，因此在深度学习中遇到的最常见错误之一是形状不匹配。

In [216]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B)  # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [217]:
tensor_A,tensor_B

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]),
 tensor([[ 7., 10.],
         [ 8., 11.],
         [ 9., 12.]]))

In [218]:
tensor_A,tensor_B.T

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]),
 tensor([[ 7.,  8.,  9.],
         [10., 11., 12.]]))

In [219]:
# 转置 tensor_B 时操作有效
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


### 5.1聚合方法

查找最小值、最大值、平均值、总和等。

In [220]:
# 创建一个张量
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

执行一些聚合方法

In [221]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # 会报错
print(f"Mean: {x.type(torch.float32).mean()}")  # 没有 float 数据类型将无法工作
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


也可以使用方法执行与上述相同的操作

In [222]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

### 5.2位置索引

In [223]:
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


### 5.3更改数据类型

默认情况下，PyTorch会使用 `torch.float32` 作为数据类型。
注意：数字越小（例如 32、16、8），计算机存储的值就越不精确。

In [224]:
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

更改为 `torch.float16`.

In [225]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

更改为 `torch.int8`

In [226]:
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

### 5.4更改形状

很多时候你会想要重塑或改变你的张量的维度而不实际改变它们内部的值。

为此，一些流行的方法是：

| 方法                | 说明                  |
|-------------------|---------------------|
| torch.reshape     | 用于改变张量形状而不改变其元素数量和值 |
| torch.Tensor.view | 用于改变张量形状而不改变其元素数量和值 |
| torch.stack ]     | 用于将多个张量沿着新的维度堆叠在一起  |
| torch.squeeze     | 用于从张量中删除所有大小为1的维度   |
| torch.unsqueeze   | 用于在张量中插入一个大小为1的维度   |
| torch.permute     | 用于重新排列张量的维度         |


In [227]:
import torch

x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

添加维度

In [228]:
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

更改视图

In [229]:
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

改变视图会改变原来的张量

In [230]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [231]:
# 将张量堆叠在一起
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

删除维度

In [232]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


在特定索引处添加维度

In [233]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


 重新排列轴值的顺序，例如将轴 0 移动到轴 1 的位置，轴 1 移动到轴 2 的位置，轴 2 移动到轴 0 的位置。

In [234]:
x_original = torch.rand(size=(224, 224, 3))

x_permuted = x_original.permute(2, 0, 1)  # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## 6.索引
Pytorch 中的索引与 Python 中的索引类似，但是有一些细微的差别。

In [235]:
import torch

x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

索引单个值

In [236]:
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


索引多个值

In [237]:
x[:, 0]

tensor([[1, 2, 3]])

In [238]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [239]:
x[:, 1, 1]

tensor([5])

In [240]:
x[0, 0, :]  # same as x[0][0]

tensor([1, 2, 3])

## 7.PyTorch tensors & NumPy

PyTorch与NumPy之间的交互是非常简单的，因为PyTorch tensors和NumPy arrays都是基于相同的C++后端的。

In [241]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

默认情况下，NumPy 数组是使用数据类型创建的float64，如果将其转换为 PyTorch 张量，将保持相同的数据类型

PyTorch 计算默认使用 `float32`.

使用 `tensor = torch.from_numpy(array).type(torch.float32)` 转换为 `float32`.


 NumPy to PyTorch

In [242]:
tensor = torch.ones(7)  # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy()  # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## 8.GPU



### 8.1检查 GPU

首先，我们需要检查是否有可用的 GPU。如果有，我们将使用它来加速我们的计算。


In [243]:
# !nvidia-smi

### 8.2让 PyTorch 在 GPU 上运行

测试 PyTorch 是否可以访问 GPU，如果可以，我们将使用它来加速我们的计算。

MacOS 上的 PyTorch 默认使用 CPU，但是可以使用 mps（Metal Performance Shaders (Apple's GPU) ） 来加速计算。

In [244]:
import torch

torch.cuda.is_available()

True

In [245]:
device = "cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu"
device

'cuda'

In [246]:
torch.cuda.device_count()

1

### 8.3将张量或模型放在 GPU 上

In [247]:
tensor = torch.tensor([1, 2, 3])

print(tensor, tensor.device)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

### 8.4将张量移回CPU


In [248]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)